spacePlane = sprites.create(img("""
    ....................................
    ........eeeee.......................
    .......edddddeee....................
    ........eeeeedddee..................
    ..........b..eeedbe.................
    ...........b....bbbe................
    ............b....bbbe...............
    .............b....bde...............
    ..............b....ede..............
    ...............b...ede..............
    ................b..ede..............
    .................b..ede.............
    ..................b.ede.............
    ...................bede.............
    ....................ede.............
    .....................e..............
"""), SpriteKind.player)
spacePlane.set_stay_in_screen(True)
info.set_life(3)
controller.move_sprite(spacePlane, 200, 200)
#spacePlane: Sprite = None
def on_a_pressed():
    dart = sprites.create_projectile_from_sprite(img("""
        ........................
        ........................
        ........................
        ........................
        .......1................
        ......1b1...............
        .......1e...eeeeeeeee...
        ........ee..eeeeeeeee...
        .........ee.eddddddde...
        ..........eeddddddddd...
        ...........ed18ddd81d...
        ............ddd444ddd...
        ............ddedddedd...
        ............ddeeeeedd...
        ........................
        ........................
    """), spacePlane, 200, 0)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)
def on_update_interval():
    bogey = sprites.create(img("""
        . . . . f f f f f f f f . . . .
        . . . f 2 2 2 2 2 2 2 2 f . . .
        . . . f 2 2 2 2 2 2 2 2 2 f . .
        . f f f 2 2 2 f f f f f f f . .
        f 2 2 f 2 2 f 8 9 9 1 1 1 9 f .
        f 2 2 f 2 2 f 8 9 9 9 1 1 9 f .
        f 2 2 f 2 2 f 8 9 9 9 9 9 9 f .
        f 2 2 f 2 2 f 8 8 8 8 8 8 8 f .
        f 2 2 f 2 2 2 f f f f f f f . .
        f 2 2 f 2 2 2 2 2 2 2 2 2 f . .
        f 2 2 f 2 2 2 2 2 2 2 2 2 f . .
        . f f f 2 2 2 f f f f 2 2 f . .
        . . . f 2 2 2 f . f 2 2 2 f . .
        . . . f 2 2 2 f . f 2 2 2 f . .
        . . . f 2 2 2 f . f 2 2 2 f . .
        . . . . f f f . . . f f f . . .
    """), SpriteKind.enemy)
    bogey.set_velocity(-100, 0)
    bogey.left = scene.screen_width()
    bogey.y = randint(0, scene.screen_height())
    bogey.set_flag(SpriteFlag.AUTO_DESTROY, True)
game.on_update_interval(500, on_update_interval)

def on_on_overlap(sprite, otherSprite):
    otherSprite.destroy()
    info.change_life_by(-1)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

def on_overlap(sprite, otherSprite):
    otherSprite.destroy()
    sprite.destroy(effects.fire, 100)
    info.change_score_by(1)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_overlap)