let spacePlane = sprites.create(img`
    ....................................
    ........eeeee.......................
    .......edddddeee....................
    ........eeeeedddee..................
    ..........b..eeedbe.................
    ...........b....bbbe................
    ............b....bbbe...............
    .............b....bde...............
    ..............b....ede..............
    ...............b...ede..............
    ................b..ede..............
    .................b..ede.............
    ..................b.ede.............
    ...................bede.............
    ....................ede.............
    .....................e..............
`, SpriteKind.Player)
spacePlane.setStayInScreen(true)
info.setLife(3)
controller.moveSprite(spacePlane, 200, 200)
// spacePlane: Sprite = None
controller.A.onEvent(ControllerButtonEvent.Pressed, function on_a_pressed() {
    let dart = sprites.createProjectileFromSprite(img`
        ........................
        ........................
        ........................
        ........................
        .......1................
        ......1b1...............
        .......1e...eeeeeeeee...
        ........ee..eeeeeeeee...
        .........ee.eddddddde...
        ..........eeddddddddd...
        ...........ed18ddd81d...
        ............ddd444ddd...
        ............ddedddedd...
        ............ddeeeeedd...
        ........................
        ........................
    `, spacePlane, 200, 0)
})
game.onUpdateInterval(500, function on_update_interval() {
    let bogey = sprites.create(img`
        . . . . f f f f f f f f . . . .
        . . . f 2 2 2 2 2 2 2 2 f . . .
        . . . f 2 2 2 2 2 2 2 2 2 f . .
        . f f f 2 2 2 f f f f f f f . .
        f 2 2 f 2 2 f 8 9 9 1 1 1 9 f .
        f 2 2 f 2 2 f 8 9 9 9 1 1 9 f .
        f 2 2 f 2 2 f 8 9 9 9 9 9 9 f .
        f 2 2 f 2 2 f 8 8 8 8 8 8 8 f .
        f 2 2 f 2 2 2 f f f f f f f . .
        f 2 2 f 2 2 2 2 2 2 2 2 2 f . .
        f 2 2 f 2 2 2 2 2 2 2 2 2 f . .
        . f f f 2 2 2 f f f f 2 2 f . .
        . . . f 2 2 2 f . f 2 2 2 f . .
        . . . f 2 2 2 f . f 2 2 2 f . .
        . . . f 2 2 2 f . f 2 2 2 f . .
        . . . . f f f . . . f f f . . .
    `, SpriteKind.Enemy)
    bogey.setVelocity(-100, 0)
    bogey.left = scene.screenWidth()
    bogey.y = randint(0, scene.screenHeight())
    bogey.setFlag(SpriteFlag.AutoDestroy, true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function on_on_overlap(sprite: Sprite, otherSprite: Sprite) {
    otherSprite.destroy()
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function on_overlap(sprite: Sprite, otherSprite: Sprite) {
    otherSprite.destroy()
    sprite.destroy(effects.fire, 100)
    info.changeScoreBy(1)
})
